MINIO_ENDPOINT_DEV="127.0.0.1:9000"
MINIO_ACCESS_KEY_DEV="test_access_key"
MINIO_SECRET_KEY_DEV="test_secret_key"

NEO4J_API_URL_DEV="http://localhost:8080"
NEO4J_ENDPOINT_DEV="neo4j://localhost:7687"
NEO4J_USERNAME_DEV="neo4j"
NEO4J_PASSWORD_DEV="test_password"
