services:

  minio:
    image: minio/minio:latest
    container_name: minio-for-testing-spatial-labeler
    ports:
      - "9000:9000"    
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  neo4j:
    image: neo4j:latest
    container_name: neo4j-for-testing-spatial-labeler
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test_password

volumes:
  minio_data:
    driver: local